import PySpice.Logging.Logging as Logging
logger = Logging.setup_logging()


from PySpice.Spice.NgSpice.Shared import NgSpiceShared


ngspice = NgSpiceShared.new_instance()

print(ngspice.exec_command('version -f'))
print(ngspice.exec_command('print all'))
print(ngspice.exec_command('devhelp'))
print(ngspice.exec_command('devhelp resistor'))

circuit = '''
* `ngspice` Sim Input for `__main__.Tb`
* Generated by `vlsirtools.NgspiceNetlister`
* 
* Anonymous `circuit.Package`
* Generated by `vlsirtools.NgspiceNetlister`
* 

.SUBCKT Tb
+ VSS 
* No parameters

vvdc
+ vdc_p VSS 
+ dc '1' 
+ ac '0' 
* No parameters


xmos
+ vdc_p vdc_p VSS VSS 
+ nmos
+ w='1u' l='1u' nf='1' m='1' 

.ENDS

xtop 0 Tb // Top-Level DUT 


.param x=1
.include "/ic_tools/miniconda3/envs/Grimoire/lib/python3.10/site-packages/hdl21/pdk/sample_pdk/resources/models.sp"
.dc xtop.vvdc.dc start=0.0 stop=1.0 step=2.0






'''

ngspice.load_circuit(circuit)
print('Loaded circuit:')
print(ngspice.listing())

print(ngspice.show('c3'))
print(ngspice.showmod('c3'))

ngspice.run()
print('Plots:', ngspice.plot_names)

print(ngspice.ressource_usage())
print(ngspice.status())

plot = ngspice.plot(simulation=None, plot_name=ngspice.last_plot)
import matplotlib.pyplot as plt

fig, ax = plt.subplots()
ax.plot(plot['V(6)']._data)

# ax.set(xlabel='time (s)', ylabel='voltage (mV)',
#        title='About as simple as it gets, folks')
ax.grid()

fig.savefig("test.png")
# plt.show()
print(plot)

# ngspice.quit()