* `ngspice` Sim Input for `__main__.Tb`
* Generated by `vlsirtools.NgspiceNetlister`
* 
* Anonymous `circuit.Package`
* Generated by `vlsirtools.NgspiceNetlister`
* 

.SUBCKT Tb
+ VSS 
* No parameters

vvdc
+ vdc_p VSS 
+ dc '1' 
+ ac '0' 
* No parameters


xmos
+ vdc_p vdc_p VSS VSS 
+ nmos
+ w='1u' l='1u' nf='1' m='1' 

.ENDS

xtop 0 Tb // Top-Level DUT 


.param x=1
.include "/ic_tools/miniconda3/envs/Grimoire/lib/python3.10/site-packages/hdl21/pdk/sample_pdk/resources/models.sp"
.dc v.xtop.vvdc 0.0 1.0 5.0