#!/usr/bin/env bash

set -ex
# start venv
uv venv .venv
source .venv/bin/activate

apt install wget
mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm ~/miniconda3/miniconda.sh

source ~/miniconda3/bin/activate
conda install python=3.10
conda install -c conda-forge pyspice


uv pip install marimo
uv pip install PySpice

apt update

apt install ngspice
apt install libngspice0 
# uv pip install pyspice
# apt-get -y install \
#     git \
#     libx11-dev \
#     libx11-xcb-dev \
#     libxrender-dev \
#     libcairo2-dev \
#     tcl8.6 \
#     tcl8.6-dev \
#     tcl-tclreadline \
#     tk-dev \
#     flex \
#     bison \
# 	libxpm-dev \
#     libjpeg-dev \
#     xterm \
#     vim-gtk3 \
#     gawk

# REPO_COMMIT_SHORT=$(echo "$XSCHEM_REPO_COMMIT" | cut -c 1-7)

# git clone --filter=blob:none "${XSCHEM_REPO_URL}" "${XSCHEM_NAME}"
# cd "${XSCHEM_NAME}"
# git checkout "${XSCHEM_REPO_COMMIT}"
# ./configure --prefix="${TOOLS}/${XSCHEM_NAME}"
# make -j"$(nproc)"
# make install

# export PATH="${PATH:+${PATH}:}/foss/tools/xschem/bin"